# Food Inspection
Profile the data sets (single- and multi-column) to understand and visualize the characteristics of the datasets and relationships between the columns relevant to the aforementioned goal. Specifically, you should perform the following tasks:

o Single-column profiling to gather various statistics and distributions of the columns.

o Find correlation between columns using association rule mining technique.

o Discovery functional dependencies from the columns.

o Find inclusion dependencies between the columns.

o Devise techniques to visualize the results of the aforementioned data profiling tasks. Explain what useful information you have garnered by performing the aforementioned tasks.

o Find data quality problems in the data using techniques taught in your course. How can you address them?

### Imports

In [1]:
import pandas as pd
import numpy as np
import itertools
from itertools import combinations
from tqdm import tqdm 
import csv
import mlxtend
from mlxtend.frequent_patterns import apriori, association_rules

### Load Dataset

In [2]:
df = pd.read_csv("Food_Inspections_20240215.csv")

# 1. Data Preparation

In [3]:
df.head()

,Inspection ID,DBA Name,AKA Name,License #,Facility Type,Risk,Address,City,State,Zip,Inspection Date,Inspection Type,Results,Violations,Latitude,Longitude,Location
0,2589375,PERFECT BEGINNINGS CHILD DEVELOPMENT CENTER,PERFECT BEGINNINGS CHILD DEVELOPMENT CENTER,2385784.0,Daycare Above and Under 2 Years,Risk 1 (High),1500 W 119TH ST,CHICAGO,IL,60643.0,02/08/2024,License,Pass,51. PLUMBING INSTALLED; PROPER BACKFLOW DEVICE...,41.677685,-87.659020,"(41.677685065833224, -87.65901954921286)"
1,2589377,BIG BOSS SPICY FRIED CHICKEN,BIG BOSS SPICY FRIED CHICKEN,2807954.0,Restaurant,Risk 1 (High),2520 S HALSTED ST,CHICAGO,IL,60608.0,02/08/2024,Canvass,Fail,23. PROPER DATE MARKING AND DISPOSITION - Comm...,41.846381,-87.646613,"(41.84638121795965, -87.64661301435865)"
2,2589348,Drummond,Drummond,23021.0,School,Risk 1 (High),1845 W Cortland ST,CHICAGO,IL,60622.0,02/08/2024,Canvass Re-Inspection,Fail,59. PREVIOUS PRIORITY FOUNDATION VIOLATION COR...,41.915886,-87.674496,"(41.91588633998172, -87.67449563016454)"
3,2589332,SUBWAY,SUBWAY,2665377.0,Restaurant,Risk 1 (High),1608 W 59TH ST,CHICAGO,IL,60636.0,02/08/2024,Canvass Re-Inspection,Pass,57. ALL FOOD EMPLOYEES HAVE FOOD HANDLER TRAIN...,41.786850,-87.664801,"(41.786849792502515, -87.66480141216883)"
4,2589295,LUCY'S,LUCY'S,2712942.0,Restaurant,Risk 1 (High),4570 N BROADWAY,CHICAGO,IL,60640.0,02/07/2024,Canvass Re-Inspection,Pass,NaN,41.965270,-87.657554,"(41.96527014438852, -87.6575542920256)"

In [4]:
df.info()
df.describe(include='all')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 267531 entries, 0 to 267530
Data columns (total 17 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   Inspection ID    267531 non-null  int64
 1   DBA Name         267531 non-null  object
 2   AKA Name         265058 non-null  object
 3   License #        267513 non-null  float64
 4   Facility Type    262416 non-null  object
 5   Risk             267450 non-null  object
 6   Address          267531 non-null  object
 7   City             267370 non-null  object
 8   State            267472 non-null  object
 9   Zip              267482 non-null  float64
 10  Inspection Date  267531 non-null  object
 11  Inspection Type  267530 non-null  object
 12  Results          267531 non-null  object
 13  Violations       194191 non-null  object
 14  Latitude         266608 non-null  float64
 15  Longitude        266608 non-null  float64
 16  Location         266608 non-null  object
dtypes: float64(4), int64(1), object(12)
memory usage: 34.7+ MB

,Inspection ID,DBA Name,AKA Name,License #,Facility Type,Risk,Address,City,State,Zip,Inspection Date,Inspection Type,Results,Violations,Latitude,Longitude,Location
count,2.675310e+05,267531,265058,2.675130e+05,262416,267450,267531,267370,267472,267482.000000,267531,267530,267531,194191,266608.000000,266608.000000,266608
unique,NaN,32165,30614,NaN,513,4,19639,78,5,NaN,3562,110,7,192923,NaN,NaN,18210
top,NaN,SUBWAY,SUBWAY,NaN,Restaurant,Risk 1 (High),11601 W TOUHY AVE,CHICAGO,IL,NaN,11/14/2013,Canvass,Pass,32. FOOD AND NON-FOOD CONTACT SURFACES PROPERL...,NaN,NaN,"(42.008536400868735, -87.91442843927047)"
freq,NaN,3552,4370,NaN,179811,196048,3273,266472,267461,NaN,185,139061,137733,11,NaN,NaN,3291
mean,1.729715e+06,NaN,NaN,1.721737e+06,NaN,NaN,NaN,NaN,NaN,60628.704040,NaN,NaN,NaN,NaN,41.880728,-87.676427,NaN
std,7.194335e+05,NaN,NaN,9.269263e+05,NaN,NaN,NaN,NaN,NaN,148.879568,NaN,NaN,NaN,NaN,0.081072,0.058636,NaN
min,4.424700e+04,NaN,NaN,0.000000e+00,NaN,NaN,NaN,NaN,NaN,10014.000000,NaN,NaN,NaN,NaN,41.644670,-87.914428,NaN
25%,1.307352e+06,NaN,NaN,1.336815e+06,NaN,NaN,NaN,NaN,NaN,60614.000000,NaN,NaN,NaN,NaN,41.831819,-87.707462,NaN
50%,1.950830e+06,NaN,NaN,2.048784e+06,NaN,NaN,NaN,NaN,NaN,60625.000000,NaN,NaN,NaN,NaN,41.891770,-87.666419,NaN
75%,2.356946e+06,NaN,NaN,2.369039e+06,NaN,NaN,NaN,NaN,NaN,60643.000000,NaN,NaN,NaN,NaN,41.939787,-87.634942,NaN
max,2.589430e+06,NaN,NaN,9.999999e+06,NaN,NaN,NaN,NaN,NaN,90504.000000,NaN,NaN,NaN,NaN,42.021064,-87.525094,NaN

### 1.1 Missing Values

In [5]:
# Count missing values
missing = df.isnull().sum()

# Percentage missing
missing_pct = (missing / len(df)) * 100

missing_df = pd.DataFrame({
    'Missing Count': missing,
    'Missing %': missing_pct
}).sort_values(by='Missing %', ascending=False)

missing_df

                 Missing Count  Missing %
Violations               73340  27.413646
Facility Type             5115   1.911928
AKA Name                  2473   0.924379
Longitude                  923   0.345007
Location                   923   0.345007
Latitude                   923   0.345007
City                       161   0.060180
Risk                        81   0.030277
State                       59   0.022054
Zip                         49   0.018316
License #                   18   0.006728
Inspection Type              1   0.000374
Inspection ID                0   0.000000
Address                      0   0.000000
DBA Name                     0   0.000000
Results                      0   0.000000
Inspection Date              0   0.000000

### 1.2 Duplicate Records
Inspection ID seems to be the primary key, hence validating if the primary key has duplicates

In [6]:
# Check duplicate Inspection IDs
duplicates = df[df.duplicated(subset=['Inspection ID'])]

len(duplicates)

0

### 1.3 Validating if 'Location' is a concatenation of 'Latitude' and 'Longitude'

In [7]:
# Keep only rows with complete geo info
location_related_columns = ["Latitude", "Longitude", "Location"]

# Count rows where ALL location-related columns are empty
count_all_empty = df[df[location_related_columns].isna().all(axis=1)].shape[0]
print(f"No. of rows where ALL of {str(location_related_columns)} are empty : {count_all_empty}")

# Count rows where AT LEAST ONE location-related column is empty
count_any_empty = df[df[location_related_columns].isna().any(axis=1)].shape[0]
print(f"No. of rows where ANY ONE of {str(location_related_columns)} is empty : {count_any_empty}")

df_location_cleaned = df.dropna(subset=location_related_columns).copy()

# Ensure numeric
df_location_cleaned["Latitude"] = df_location_cleaned["Latitude"].astype(float)
df_location_cleaned["Longitude"] = df_location_cleaned["Longitude"].astype(float)

# Extract numbers from Location (simple approach)
df_location_cleaned["Location"] = df_location_cleaned["Location"].astype(str)
df_location_cleaned[["loc_lat", "loc_lon"]] = df_location_cleaned["Location"].str.extract(r"(-?\d+\.\d+)[^\d-]+(-?\d+\.\d+)")

df_location_cleaned["loc_lat"] = df_location_cleaned["loc_lat"].astype(float)
df_location_cleaned["loc_lon"] = df_location_cleaned["loc_lon"].astype(float)

# Compare with small tolerance
tolerance = 0.0001

mismatches = df_location_cleaned[
    (np.abs(df_location_cleaned["Latitude"] - df_location_cleaned["loc_lat"]) > tolerance) |
    (np.abs(df_location_cleaned["Longitude"] - df_location_cleaned["loc_lon"]) > tolerance)
]

print(f"Total rows checked where ALL of {str(location_related_columns)} are not empty: {len(df_location_cleaned):,}")
print(f"Mismatches         : {len(mismatches):,}")

# Drop helper columns
df_location_cleaned = df_location_cleaned.drop(columns=["loc_lat", "loc_lon"])

No. of rows where ALL of ['Latitude', 'Longitude', 'Location'] are empty : 923
No. of rows where ANY ONE of ['Latitude', 'Longitude', 'Location'] is empty : 923
Total rows checked where ALL of ['Latitude', 'Longitude', 'Location'] are not empty: 266,608
Mismatches         : 0

### 1.4 Inconsistent Formats and Invalid Values
Descriptions of the data elements included in the dataset: https://data.cityofchicago.org/api/assets/BAD5301B-681A-4202-9D25-51B2CAE672FF

#### 1.4.1 Facility Type
Each establishment is described by one of the following: bakery, banquet hall, candy store, caterer, coffee shop, day care center (for ages less than 2), day care center (for ages 2 – 6), day care center (combo, for ages less than 2 and 2 – 6 combined), gas station, Golden Diner, grocery store, hospital, long term care center(nursing home), liquor store, mobile food dispenser, restaurant, paleteria, school, shelter, tavern, social club, wholesaler, or Wrigley Field Rooftop.

In [8]:
df_facility = df_location_cleaned.copy()
df_facility['Facility Type'] = (df_facility['Facility Type'].str.upper().str.strip())

# Get unique, sorted values
sorted_facilities = sorted(df_facility['Facility Type'].dropna().unique())

# Print each on a new line
for facility in sorted_facilities:
    print(facility)

(CONVENIENCE STORE)
(GAS STATION)
1005 NURSING HOME
1023
1023 CHILDERN'S SERVICE S FACILITY
1023 CHILDERN'S SERVICES FACILITY
1023 CHILDREN'S SERVICES FACILITY
1023-CHILDREN'S SERVICES FACILITY
1475 LIQUOR
15 MONTS TO 5 YEARS OLD
1584-DAY CARE ABOVE 2 YEARS
A-NOT-FOR-PROFIT CHEF TRAINING PROGRAM
ADULT DAYCARE
ADULT FAMILY CARE CENTER
AFTER SCHOOL CARE
AFTER SCHOOL PROGRAM
AIRPORT LOUNGE
ALTERNATIVE SCHOOL
ANIMAL SHELTER CAFE PERMIT
ARCHDIOCESE
ART CENTER
ART GALLERY
ART GALLERY W/WINE AND BEER
ASSISSTED LIVING
ASSISTED LIVING
ASSISTED LIVING SENIOR CARE
BAKERY
BAKERY/ RESTAURANT
BAKERY/DELI
BAKERY/GROCERY
BAKERY/RESTAURANT
BANQUET
BANQUET DINING
BANQUET FACILITY
BANQUET HALL
BANQUET HALL/CATERING
BANQUET ROOM
BANQUET ROOMS
BANQUET/KITCHEN
BANQUETS
BANQUETS/ROOM SERVICE
BAR
BAR/GRILL
BEFORE AND AFTER SCHOOL PROGRAM
BEVERAGE/SILVERWARE WAREHOUSE
BLOCKBUSTER VIDEO
BOOK STORE
BOWLING LANES/BANQUETS
BOYS AND GIRLS CLUB
BREWERY
BREWPUB
BUTCHER SHOP
CAFE
CAFE/STORE
CAFETERIA
CANDY
CANDY MAKER
CANDY SHOP
CANDY STORE
CANDY/GELATO
CAR WASH
CAT/LIQUOR
CATERED EVENTS
CATERED LIQUOR
CATERING
CATERING AND WHOLESALE
CATERING/BANQUET
CATERING/CAFE
CELL PHONE STORE
CHARITY AID KITCHEN
CHARTER
CHARTER SCHOOL
CHARTER SCHOOL CAFETERIA
CHARTER SCHOOL/CAFETERIA
CHICAGO PARK DISTRICT
CHILDERN ACTIVITY FACILITY
CHILDERN'S SERVICE FACILITY
CHILDERN'S SERVICES  FACILITY
CHILDREN'S SERVICES FACILITY
CHILDRENS SERVICES FACILITY
CHINESE HERBS
CHURCH
CHURCH (SPECIAL EVENTS)
CHURCH KITCHEN
CHURCH/AFTER SCHOOL PROGRAM
CHURCH/DAY CARE
CHURCH/SPECIAL EVENTS
CITY OF CHICAGO COLLEGE
CLOTHING STORE
COFFEE
COFFEE  SHOP
COFFEE AND/OR DRINKS
COFFEE CART
COFFEE KIOSK
COFFEE ROASTER
COFFEE SHOP
COFFEE VENDING MACHINE
COFFEE/TEA
COLD STORAGE FACILITY
COLD/FROZEN FOOD STORAGE
COLLEGE
COMMIASARY
COMMISARY
COMMISSARY
COMMISSARY FOR SOFT SERVE ICE CREAM TRUCKS
CONVENIENCE
CONVENIENCE STORE
CONVENIENCE/DRUG STORE
CONVENIENCE/GAS STATION
CONVENIENT STORE
CONVNIENCE STORE
COOKING CLASS
COOKING SCHOOL
CULINARY ARTS SCHOOL
CULINARY CLASS ROOMS
CULINARY KITCHEN
CULINARY SCHOOL
CUSTOM POULTRY SLAUGHTER
DAY CARE
DAY CARE 1023
DAY CARE 2-14
DAY CARE COMBO (1586)
DAY CARE FACILITY
DAY SPA
DAYCARE
DAYCARE (2 - 6 YEARS)
DAYCARE (2 YEARS)
DAYCARE (UNDER 2 YEARS)
DAYCARE 1586
DAYCARE 2 YRS TO 12 YRS
DAYCARE 2-6, UNDER 6
DAYCARE 6 WKS-5YRS
DAYCARE ABOVE AND UNDER 2 YEARS
DAYCARE COMBO
DAYCARE COMBO 1586
DAYCARE NIGHT
DELI
DELI/BAKERY
DINING HALL
DISTILLERY WITH TASTING ROOM
DISTRIBUTION CENTER
DISTRIBUTOR
DOLLAR & GROCERY STORE
DOLLAR STORE
DOLLAR STORE WITH GROCERY
DOLLAR TREE
DONUT SHOP
DRUG STORE
DRUG STORE/GROCERY
DRUG STORE/W/ FOOD
DRUG TREATMENT FACILITY
DRUG/FOOD STORE
EMPLOYEE KITCHEN
EVENT CENTER
EVENT SPACE
EVENT VENU
EXERCISE AND NUTRITION BAR
FARMER'S MARKET
FISH MARKET
FITNESS CENTER
FITNESS STUDIO
FLEA MARKET
FOOD BOOTH
FOOD PANTRY
FOOD PANTRY/CHURCH
FRENCH MARKET SPACE
FROZEN DESSERT PUSHCARTS
FROZEN DESSERTS DISPENSER -NON MOTORIZED
FROZEN DESSERTS DISPENSER-NON-MOTORIZED
FURNITURE STORE
GAS STATION
GAS STATION /GROCERY
GAS STATION /SUBWAY MINI MART.
GAS STATION FOOD STORE
GAS STATION STORE
GAS STATION/ GROCERY STORE
GAS STATION/CONVENIENCE STORE
GAS STATION/FOOD
GAS STATION/GROCERY
GAS STATION/MINI MART
GAS STATION/RESTAURANT
GAS STATION/STORE
GAS STATION/STORE GROCERY
GAS/MINI MART
GELATO SHOP
GENERAL STORE
GIFT SHOP
GOLDEN DINER
GOLF COURSE
GOLF COURSE CONNCESSION STAND
GREENHOUSE
GROCERY
GROCERY & LIQUOR STORE
GROCERY & RESTAURANT
GROCERY AND BUTCHER
GROCERY STORE
GROCERY STORE / GAS STATION
GROCERY STORE /PHARMACY
GROCERY STORE/ RESTAURANT
GROCERY STORE/BAKERY
GROCERY STORE/COOKING SCHOOL
GROCERY STORE/DELI
GROCERY STORE/GAS STATION
GROCERY STORE/RESTAURANT
GROCERY STORE/TAQUERIA
GROCERY(GAS STATION)
GROCERY(SUSHI PREP)
GROCERY/ RESTAURANT
GROCERY/BAKERY
GROCERY/BUTCHER
GROCERY/CAFE
GROCERY/DELI
GROCERY/DOLLAR STORE
GROCERY/DRUG STORE
GROCERY/GAS STATION
GROCERY/LIQUOR
GROCERY/LIQUOR STORE
GROCERY/RESTAURANT
GROCERY/SERVICE GAS STATION
GROCERY/TAQUERIA
GYM
GYM STORE
HAIR SALON
HEALTH CARE STORE
HEALTH CENTER
HEALTH CENTER/NUTRITION CLASSES
HEALTH CLUB
HEALTH FOOD STORE
HELICOPTER TERMINAL
HERABALIFE
HERBAL
HERBAL DRINKS
HERBAL LIFE
HERBAL LIFE SHOP
HERBAL MEDICINE
HERBAL REMEDY
HERBAL STORE
HERBALCAL
HERBALIFE
HERBALIFE NUTRITION
HERBALIFE STORE
HERBALIFE/ZUMBA
HOOKA BAR
HOOKA LOUNGE
HOSPITAL
HOSTEL
HOT DOG CART
HOT DOG STATION
HOTEL
ICE CREAM
ICE CREAM PARLOR
ICE CREAM SHOP
ILLEGAL VENDOR
INCUBATOR
INTERNET CAFE
JUICE AND SALAD BAR
JUICE BAR
JUICE BAR/GROCERY
KIDS CAFE
KIDS CAFE'
KIOSK
KITCHEN
KITCHEN DEMO
LAUNDROMAT
LINITED BUSINESS
LIQOUR BREWERY TASTING
LIQUOR
LIQUOR CONSUMPTION ON PREMISES.
LIQUOR STORE
LIQUOR/COFFEE KIOSK
LIQUOR/GROCERY STORE/BAR
LIQUORE STORE/BAR
LIVE BUTCHER
LIVE POULTRY
LIVE POULTRY SLAUGHTER FACILITY
LONG TERM CARE
LONG TERM CARE FACILITY
LONG-TERM CARE
LONG-TERM CARE FACILITY
LOUNGE
LOUNGE/BANQUET HALL
MAIN KITCHEN
MASSAGE BAR
MEAT MARKET
MEAT PACKING
MEXICAN CANDY STORE
MILK TEA
MOBIL FOOD 1315
MOBIL FOOD PREPARED
MOBILE DESSERT CART
MOBILE DESSERT VENDOR
MOBILE DESSERTS VENDOR
MOBILE FOOD
MOBILE FOOD DESSERTS VENDOR
MOBILE FOOD DISPENSER
MOBILE FOOD PREPARER
MOBILE FOOD TRUCK
MOBILE FROZEN DESSERT DISP/NON-MOTORIZED
MOBILE FROZEN DESSERT DISPENSER_NON  MOTORIZED.
MOBILE FROZEN DESSERT VENDOR
MOBILE FROZEN DESSERTS DISPENSER-NON- MOTORIZED
MOBILE FROZEN DESSERTS DISPENSER-NON-MOTOR
MOBILE FROZEN DESSERTS DISPENSER-NON-MOTORIZED
MOBILE FROZEN DESSERTS VENDOR
MOBILE PREPARED FOOD VENDOR
MOBILE PUSH CART
MOBILPREPARED FOOD VENDOR
MOVIE THEATER
MOVIE THEATRE
MUSEUM/GALLERY
MUSIC VENUE
NAIL SHOP
NAVY PIER KIOSK
NEWSSTAND
NIGHT CLUB
NON -PROFIT
NON-FOR PROFIT BASEMENT KIT
NORTHERLY ISLAND
NOT FOR PROFIT
NOT-FOR-PROFIT CLUB
NP-KIOSK
NURSING HOME
NUTRITION SHAKES
NUTRITION STORE
NUTRITION..SMOOTHIES/SHAKES
NUTRITION/HERBALIFE
OTHER
OUTREACH CULINARY KITCHEN
PACKAGED FOOD DISTRIBUTION
PACKAGED HEALTH FOODS
PACKAGED LIQUOR
PALETERIA
PALETERIA /ICECREAM SHOP
PANTRY
PASTRY SCHOOL
PEDDLER
PHARMACY
POOL
POP-UP ESTABLISHMENT HOST-TIER II
POP-UP ESTABLISHMENT HOST-TIER III
POP-UP FOOD ESTABLISHMENT USER-TIER I
POP-UP FOOD ESTABLISHMENT USER-TIER II
POPCORN CORN
POPCORN SHOP
POULTRY SLAUGHTER
PRE PACKAGED
PREP INSIDE SCHOOL
PREPACAKAGED FOODS
PREPACKAGE MEAL DISTRIBUTOR (1006 RETAIL)
PRIVATE CLUB
PRIVATE EVENT SPACE
PRIVATE SCHOOL
PRODUCE STAND
PRODUCE VENDOR
PROTEIN SHAKE BAR
PUBLIC SHCOOL
PUSH CARTS
REGULATED BUSINESS
REHAB CENTER
RELIGIOUS
REPACKAGING PLANT
REST/GROCERY
REST/GYM
REST/ROOFTOP
RESTAURANT
RESTAURANT AND LIQUOR
RESTAURANT(PROTEIN SHAKE BAR)
RESTAURANT.BANQUET HALLS
RESTAURANT/BAKERY
RESTAURANT/BAR
RESTAURANT/BAR/THEATER
RESTAURANT/GROCERY
RESTAURANT/GROCERY STORE
RESTAURANT/HOSPITAL
RESTAURANT/LIQUOR
RESTUARANT AND BAR
RETAIL
RETAIL FOOD
RETAIL FOOD/GAS STATION
RETAIL SALES
RETAIL STORE
RETAIL STORE OFFERS COOKING CLASSES
RETAIL WINE/WINE BAR
RIVERWALK
RIVERWALK CAFE
ROOF TOP
ROOF TOPS
ROOFTOP
ROOFTOP PATIO
ROOFTOPS
ROOM SERVICE
SCHOOL
SCHOOL CAFETERIA
SENIOR DAY CARE
SERVICE BAR/THEATRE
SERVICE GAS STATION
SHAKES/TEAS
SHARED KITCHEN
SHARED KITCHEN USER (LONG TERM)
SHARED KITCHEN USER (LONG TREM)
SHARED KITCHEN USER (SHORT TERM)
SHELTER
SHUFFLEBOARD CLUB WITH BAR
SLAUGHTER HOUSE/ GROCERY
SMOKEHOUSE
SMOOTHIE BAR
SNACK SHOP
SOCIAL CLUB
SOUP KITCHEN
SPA
SPECIAL EVENT
STADIUM
STORE
SUMMER FEEDING
SUMMER FEEDING PREP AREA
SUPPORTIVE LIVING
SUSHI COUNTER
TAP ROOM/TAVERN/LIQUOR STORE
TAVERN
TAVERN-LIQUOR
TAVERN/1006
TAVERN/BAR
TAVERN/LIQUOR
TAVERN/PACKAGED GOODS
TAVERN/RESTAURANT
TEA STORE
TEACHING SCHOOL
TEMPORARY KIOSK
TENT RSTAURANT
TEST KITCHEN/ STORAGE
THEATER
THEATER/BAR
THEATRE
TOBACCO STORE
TRUCK
UNIVERSITY CAFETERIA
UNLICENSED FACILITY
UNUSED STORAGE
URBAN FARM
VENDING COMMISSARY
VENDING MACHINE
VFW HALL
VIDEO STORE
WAREHOUSE
WATERMELON HOUSE
WEIGHT LOSS PROGRAM
WHOLESALE
WHOLESALE & RETAIL
WHOLESALE BAKERY
WINE STORE
WINE TASTING BAR
WRIGLEY ROOF TOP
WRIGLEY ROOFTOP
YOUTH HOUSING

#### 1.4.2 City

In [9]:
df_city = df_location_cleaned.copy()
df_city['City'] = (df_city['City'].str.upper().str.strip())

sorted_cities = sorted(df_city['City'].dropna().unique())

for city in sorted_cities:
    print(city)

312CHICAGO
ALSIP
BLUE ISLAND
CCHICAGO
CHARLES A HAYES
CHCHICAGO
CHCICAGO
CHICAGO
CHICAGO.
CHICAGOBEDFORD PARK
CHICAGOC
CHICAGOCHICAGO
CHICAGOI
CHICAGOO
INACTIVE
LOMBARD
SUMMIT
WESTMONT

#### 1.4.3 State

In [10]:
df_state = df_location_cleaned.copy()
df_state['State'].value_counts(dropna=False)

State
IL     266549
NaN        59
Name: count, dtype: int64

#### 1.4.4 Inspection Date

In [11]:
future_cutoff = pd.Timestamp("2024-02-15")
df_inspection_date = df_location_cleaned.copy()

# Convert date
df_inspection_date['Inspection Date'] = pd.to_datetime(df['Inspection Date'], errors='coerce')

# Future dates
future_dates = df_inspection_date[df_inspection_date['Inspection Date'] > future_cutoff]

len(future_dates)

0

#### 1.4.5 Inspection Type

In [13]:
df_inspection_type = df_location_cleaned.copy()

df_inspection_type['Inspection Type'] = (
    df_inspection_type['Inspection Type']
    .str.upper()
    .str.strip()
)

sorted_insp_types = sorted(df_inspection_type['Inspection Type'].dropna().unique())

for insp_types in sorted_insp_types:
    print(insp_types)

1315 LICENSE REINSPECTION
ADDENDUM
ASSESSMENT
BUSINESS NOT LOCATED
CANVAS
CANVASS
CANVASS FOR RIB FEST
CANVASS RE INSPECTION OF CLOSE UP
CANVASS RE-INSPECTION
CANVASS SCHOOL/SPECIAL EVENT
CANVASS SPECIAL EVENTS
CANVASS/SPECIAL EVENT
CHANGED COURT DATE
CITATION RE-ISSUED
CITF
CLOSE-UP/COMPLAINT REINSPECTION
COMPLAINT
COMPLAINT RE-INSPECTION
COMPLAINT-FIRE
COMPLAINT-FIRE RE-INSPECTION
CONSULTATION
CORRECTIVE ACTION
COVID COMPLAINT
DAY CARE LICENSE RENEWAL
DUPLICATED
ERROR SAVE
EXPANSION
FINISH COMPLAINT INSPECTION FROM 5-18-10
FIRE
FIRE COMPLAINT
FIRE/COMPLAIN
HACCP QUESTIONAIRE
ILLEGAL OPERATION
KIDS CAFE
KIDS CAFE'
KITCHEN CLOSED FOR RENOVATION
LICENSE
LICENSE CANCELED BY OWNER
LICENSE CONSULTATION
LICENSE DAYCARE 1586
LICENSE RE-INSPECTION
LICENSE RENEWAL FOR DAYCARE
LICENSE RENEWAL INSPECTION FOR DAYCARE
LICENSE REQUEST
LICENSE TASK 1474
LICENSE TASK FORCE / NOT -FOR-PROFIT CLU
LICENSE TASK FORCE / NOT -FOR-PROFIT CLUB
LICENSE WRONG ADDRESS
LICENSE-TASK FORCE
LICENSE/NOT READY
LIQOUR TASK FORCE NOT READY
LIQUOR CATERING
NO ENTRY
NO ENTRY-SHORT COMPLAINT)
NON-INSPECTION
NOT READY
O.B.
OUT OF BUSINESS
OUT OFBUSINESS
OWNER SUSPENDED OPERATION/LICENSE
PACKAGE LIQUOR 1474
POSSIBLE FBI
PRE-LICENSE CONSULTATION
RE-INSPECTION OF CLOSE-UP
RECALL INSPECTION
RECENT INSPECTION
REINSPECTION
REINSPECTION OF 48 HOUR NOTICE
SAMPLE COLLECTION
SFP
SFP RECENTLY INSPECTED
SFP/COMPLAINT
SHORT FORM COMPLAINT
SHORT FORM FIRE-COMPLAINT
SMOKING COMPLAINT
SPECIAL EVENTS (FESTIVALS)
SPECIAL TASK FORCE
SUMMER FEEDING
SUSPECTED FOOD POISONING
SUSPECTED FOOD POISONING RE-INSPECTION
TAG REMOVAL
TASK FORCE
TASK FORCE FOR LIQUOR 1474
TASK FORCE LIQUOR (1481)
TASK FORCE LIQUOR 1470
TASK FORCE LIQUOR 1474
TASK FORCE LIQUOR 1475
TASK FORCE LIQUOR CATERING
TASK FORCE LIQUOR INSPECTION 1474
TASK FORCE NIGHT
TASK FORCE NOT READY
TASK FORCE PACKAGE GOODS 1474
TASK FORCE PACKAGE LIQUOR
TASK FORCE(1470) LIQUOR TAVERN
TASKFORCE
TASTE OF CHICAGO
TAVERN 1470
TWO PEOPLE ATE AND GOT SICK.

## IGNORE: Git stuff

In [14]:
!git clone https://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@github.com/gubudoos/Data-Prep-GP.git

Cloning into 'Data-Prep-GP'...
remote: Enumerating objects: 30, done.
remote: Counting objects: 100% (30/30), done.
remote: Compressing objects: 100% (29/29), done.
remote: Total 30 (delta 11), reused 0 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (30/30), 67.32 KiB | 2.24 MiB/s, done.
Resolving deltas: 100% (11/11), done.

In [28]:
!git init

Reinitialized existing Git repository in /home/msds/pranav025/data-prep/.git/

In [20]:
!git add main.ipynb

In [21]:
!git commit -m "Added main NB with pre-preprocessing"

[master (root-commit) 637e993] Added main NB with pre-preprocessing
 Committer: #NAGARAJAN PRANAV# <pranav025@TC2N04.cm.cluster>
Your name and email address were configured automatically based
on your username and hostname. Please check that they are accurate.
You can suppress this message by setting them explicitly. Run the
following command and follow the instructions in your editor to edit
your configuration file:

    git config --global --edit

After doing this, you may fix the identity used for this commit with:

    git commit --amend --reset-author

 1 file changed, 1722 insertions(+)
 create mode 100644 main.ipynb

In [27]:
!git push origin main

error: src refspec main does not match any
error: failed to push some refs to 'origin'