## Food Inspection

•	Profile the data sets (single- and multi-column) to understand and visualize the characteristics of the datasets and relationships between the columns relevant to the aforementioned goal. Specifically, you should perform the following tasks:

o	Single-column profiling to gather various statistics and distributions of the columns.

o	Find correlation between columns using association rule mining technique.

o	Discovery functional dependencies from the columns.

o	Find inclusion dependencies between the columns.

o	Devise techniques to visualize the results of the aforementioned data profiling tasks. Explain what useful information you have garnered by performing the aforementioned tasks.

o	Find data quality problems in the data using techniques taught in your course. How can you address them?

### Imports

In [2]:
import pandas as pd
import csv
import os
import sys

### Load CSV

In [3]:
df = pd.read_csv('Food_Inspections_20240215.csv')

In [5]:
df.head()

,Inspection ID,DBA Name,AKA Name,License #,Facility Type,Risk,Address,City,State,Zip,Inspection Date,Inspection Type,Results,Violations,Latitude,Longitude,Location
0,2589375,PERFECT BEGINNINGS CHILD DEVELOPMENT CENTER,PERFECT BEGINNINGS CHILD DEVELOPMENT CENTER,2385784.0,Daycare Above and Under 2 Years,Risk 1 (High),1500 W 119TH ST,CHICAGO,IL,60643.0,02/08/2024,License,Pass,51. PLUMBING INSTALLED; PROPER BACKFLOW DEVICE...,41.677685,-87.659020,"(41.677685065833224, -87.65901954921286)"
1,2589377,BIG BOSS SPICY FRIED CHICKEN,BIG BOSS SPICY FRIED CHICKEN,2807954.0,Restaurant,Risk 1 (High),2520 S HALSTED ST,CHICAGO,IL,60608.0,02/08/2024,Canvass,Fail,23. PROPER DATE MARKING AND DISPOSITION - Comm...,41.846381,-87.646613,"(41.84638121795965, -87.64661301435865)"
2,2589348,Drummond,Drummond,23021.0,School,Risk 1 (High),1845 W Cortland ST,CHICAGO,IL,60622.0,02/08/2024,Canvass Re-Inspection,Fail,59. PREVIOUS PRIORITY FOUNDATION VIOLATION COR...,41.915886,-87.674496,"(41.91588633998172, -87.67449563016454)"
3,2589332,SUBWAY,SUBWAY,2665377.0,Restaurant,Risk 1 (High),1608 W 59TH ST,CHICAGO,IL,60636.0,02/08/2024,Canvass Re-Inspection,Pass,57. ALL FOOD EMPLOYEES HAVE FOOD HANDLER TRAIN...,41.786850,-87.664801,"(41.786849792502515, -87.66480141216883)"
4,2589295,LUCY'S,LUCY'S,2712942.0,Restaurant,Risk 1 (High),4570 N BROADWAY,CHICAGO,IL,60640.0,02/07/2024,Canvass Re-Inspection,Pass,NaN,41.965270,-87.657554,"(41.96527014438852, -87.6575542920256)"

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 267531 entries, 0 to 267530
Data columns (total 17 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   Inspection ID    267531 non-null  int64
 1   DBA Name         267531 non-null  object
 2   AKA Name         265058 non-null  object
 3   License #        267513 non-null  float64
 4   Facility Type    262416 non-null  object
 5   Risk             267450 non-null  object
 6   Address          267531 non-null  object
 7   City             267370 non-null  object
 8   State            267472 non-null  object
 9   Zip              267482 non-null  float64
 10  Inspection Date  267531 non-null  object
 11  Inspection Type  267530 non-null  object
 12  Results          267531 non-null  object
 13  Violations       194191 non-null  object
 14  Latitude         266608 non-null  float64
 15  Longitude        266608 non-null  float64
 16  Location         266608 non-null  object
dtypes: float64(4), int64(1), object(12)
memory usage: 34.7+ MB

In [7]:
df.describe()

,Inspection ID,License #,Zip,Latitude,Longitude
count,2.675310e+05,2.675130e+05,267482.000000,266608.000000,266608.000000
mean,1.729715e+06,1.721737e+06,60628.704040,41.880728,-87.676427
std,7.194335e+05,9.269263e+05,148.879568,0.081072,0.058636
min,4.424700e+04,0.000000e+00,10014.000000,41.644670,-87.914428
25%,1.307352e+06,1.336815e+06,60614.000000,41.831819,-87.707462
50%,1.950830e+06,2.048784e+06,60625.000000,41.891770,-87.666419
75%,2.356946e+06,2.369039e+06,60643.000000,41.939787,-87.634942
max,2.589430e+06,9.999999e+06,90504.000000,42.021064,-87.525094

In [8]:
df.dtypes

Inspection ID        int64
DBA Name            object
AKA Name            object
License #          float64
Facility Type       object
Risk                object
Address             object
City                object
State               object
Zip                float64
Inspection Date     object
Inspection Type     object
Results             object
Violations          object
Latitude           float64
Longitude          float64
Location            object
dtype: object